### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by anandinmaddy** [SurveyMonkey/surveymonkey-android-sdk#13]
App is crashing in V 1.0.5.

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/TintManager;
                                                                            at android.support.design.widget.TabLayout$TabView.<init>(TabLayout.java:1185)
                                                                            at android.support.design.widget.TabLayout.createTabView(TabLayout.java:656)
                                                                            at android.support.design.widget.TabLayout.addTabView(TabLayout.java:695)
                                                                            at android.support.design.widget.TabLayout.addTab(TabLayout.java:386)
                                                                            at android.support.design.widget.TabLayout.addTab(TabLayout.java:361)

**Comment by anandinmaddy** [comment]
@benleiken please check on the above issue

**Comment by benleiken** [comment]
@anandinmaddy looks like you might be using the design support library - make sure it's up to date. the sdk uses 'com.android.support:appcompat-v7:23.2.0` so `com.android.support:design:23.2.0` should do the trick.

see http://stackoverflow.com/a/36004963/2049716 for more info and let me know if that doesn't fix your issue.
