### ISSUE TITLE
StrictMode reports an error 

### ISSUE THREAD

**Issue by ber4444** [SurveyMonkey/surveymonkey-android-sdk#15]
```
 A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                    java.lang.Throwable: Explicit termination method 'end' not called
                                                                        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                        at java.util.zip.Inflater.<init>(Inflater.java:82)
                                                                        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
                                                                        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
                                                                        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:827)
                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
                                                                        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                                                                        at com.surveymonkey.surveymonkeyandroidsdk.loaders.RetrieveSPageTask.doInBackground(RetrieveSPageTask.java:30)
                                                                        at com.surveymonkey.surveymonkeyandroidsdk.loaders.RetrieveSPageTask.doInBackground(RetrieveSPageTask.java:20)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
```

**Comment by benleiken** [comment]
Thanks @ber4444, we'll have this fixed in our next release.

**Comment by ayeung** [comment]
Hi @ber4444 Sorry for the late response,  would it be possible for you to provide code snippet (if applicable), steps to reproduce the issue, and any environment details that would be helpful?
