### ISSUE TITLE
SSL handshake aborted - When launching the Survey

### ISSUE THREAD

**Issue by mangarajmadhu** [SurveyMonkey/surveymonkey-android-sdk#25]
I am getting this error on Android 2.3.3 Samsung tablet.
Here is the complete trace:
`W/Server error: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x32d9f0: Failure in SSL library, usually a protocol error
                                                                       error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:658 0xad1276af:0x00000000)
                                                                           at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
                                                                           at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:474)
                                                                           at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
                                                                           at org.apache.harmony.luni.internal.net.www.protocol.http.HttpConnection.setupSecureSocket(HttpConnection.java:185)
                                                                           at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:433)
                                                                           at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl$HttpsEngine.makeConnection(HttpsURLConnectionImpl.java:387)
                                                                           at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.retrieveResponse(HttpURLConnectionImpl.java:1018)
                                                                           at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:512)
                                                                           at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:258)
                                                                           at com.surveymonkey.surveymonkeyandroidsdk.loaders.RetrieveSPageTask.doInBackground(RetrieveSPageTask.java:30)
                                                                           at com.surveymonkey.surveymonkeyandroidsdk.loaders.RetrieveSPageTask.doInBackground(RetrieveSPageTask.java:20)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:185)
                                                                           at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:138)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
                                                                           at java.lang.Thread.run(Thread.java:1019)`

**Comment by ayeung** [comment]
Sorry, we will be bumping minimum api support to API level 16.  Please file another issue if this continues to be a problem API 16 and above.  Thanks!
