### ISSUE TITLE
Survey screen not responding when changing the orientation while loading survey

### ISSUE THREAD

**Issue by mangarajmadhu** [SurveyMonkey/surveymonkey-android-sdk#26]
when I am changing the orientation of my Samsung tablet, while the survey screen is loading, the Survey screen hangs up with a black background and the Application became unresponsive.

Details of my test device:
Samsung- GT-P7500
Android version-3.1

Please let me know How can I handle this Issue?

**Comment by h4rib0** [comment]
Had the same experience on a Nexus 5
Android version 5.1.1

**Comment by ayeung** [comment]
@mangarajmadhu @h4rib0 Sorry for the late response.  I tried this on a Nexus 7: 6.0.1 and I couldn't reproduce this issue.  Could you provide sample code, reproduction steps, and environment that you are using (device, os etc)?

**Comment by h4rib0** [comment]
@ayeung 
Thanks for the reply. but this is no longer relevant for me. Meanwhile I am working for another company

**Comment by adrianolc** [comment]
I got this problem also on SMFeedbackFragment, the problem is you don't dismiss the progress dialog when Android destroy the fragment.

Bellow you can find the stacktrace:

android.view.WindowLeaked: Activity pl.tablica2.app.safedeal.activity.SurveyActivity has leaked window DecorView@e1b8729[] that was originally added here
                                                              at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
                                                              at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                              at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                              at android.app.Dialog.show(Dialog.java:330)
                                                              at android.app.ProgressDialog.show(ProgressDialog.java:185)
                                                              at android.app.ProgressDialog.show(ProgressDialog.java:142)
                                                              at android.app.ProgressDialog.show(ProgressDialog.java:127)
                                                              at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment.loadSurveyPage(SMFeedbackFragment.java:138)
                                                              at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment.onViewCreated(SMFeedbackFragment.java:123)
                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                              at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                              at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                              at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                              at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                              at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                                                              at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
                                                              at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
                                                              at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
                                                              at android.app.Activity.performStart(Activity.java:6992)
                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                              at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                              at android.os.Looper.loop(Looper.java:164)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by thiagokimo** [comment]
+1
