### ISSUE TITLE
CustomVariables cannot contain "blank character"?  org.json.JSONException: No value for survey_status

### ISSUE THREAD

**Issue by zhihuitang** [SurveyMonkey/surveymonkey-android-sdk#33]
We are platinum user(AnvändarId: thomas.nilsson.se). We implemented surveymonkey in our both Android and iOS app. In iOS app, the surveymonkey works fine. 
But in Android we found a problem:

```
surveyMonkey.startSMFeedbackActivityForResult(this,SM_REQUEST_CODE, id);
```
The code above it works fine.

But 
```
surveyMonkey.startSMFeedbackActivityForResult(this, SM_REQUEST_CODE, id, getCustomVariables());
```
not working, it throw crash as follows:

```
06-02 09:08:51.165 24738-24780/com.halebop.servicetips.test W/Server error: java.net.ProtocolException: Unexpected status line: <html>
                                                                                at com.android.okhttp.internal.http.StatusLine.parse(StatusLine.java:54)
                                                                                at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                                                at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                                                at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
                                                                                at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
                                                                                at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                                at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                                                                                at com.surveymonkey.surveymonkeyandroidsdk.loaders.RetrieveSPageTask.doInBackground(RetrieveSPageTask.java:30)
                                                                                at com.surveymonkey.surveymonkeyandroidsdk.loaders.RetrieveSPageTask.doInBackground(RetrieveSPageTask.java:20)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
06-02 09:08:51.165 24738-24738/com.halebop.servicetips.test W/System.err: org.json.JSONException: No value for survey_status
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at org.json.JSONObject.getJSONObject(JSONObject.java:609)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at com.surveymonkey.surveymonkeyandroidsdk.SurveyMonkey$2.onPostExecute(SurveyMonkey.java:159)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at com.surveymonkey.surveymonkeyandroidsdk.SurveyMonkey$2.onPostExecute(SurveyMonkey.java:154)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:651)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at android.os.AsyncTask.-wrap1(AsyncTask.java)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-02 09:08:51.168 24738-24738/com.halebop.servicetips.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

From Charles proxy we can see the request():
```
https://www.surveymonkey.com/r/xxxxxx?tenant_id=telia-test&channel_name=telia-test-Android&user_id=xxxxx&os=Android&os_version=6.0&platform=Nexus
```

The response is:
`400 Bad Request`

**Comment by zhihuitang** [comment]
Found the reason,it turns out to be that the value of variable CANNOT contains "**blank character**"
when my customVariables is 
`{"os":"Android","os_version":"6.0","platform":"Nexus5","app_version":"1.20(1)"}`. It works fine.

But if my customVariables is 
`{"os":"Android","os_version":"6.0","platform":"Nexus 5","app_version":"1.20(1)"}`. It throw exception as above.

Why there is limitation like this?

**Comment by zhihuitang** [comment]
You guys don't care? @benleiken

**Comment by benleiken** [comment]
@zhihuitang My sincere apologies for the delayed response. The documentation should have made it clearer that we expect URL-encoded custom variable values -- i.e. no spaces. In the next version of the SDK, we'll URL encode your custom variables for you, but for now it's your responsibility to URL-encode them.

**Comment by zhihuitang** [comment]
Good to hear from you you @benleiken. thanks

**Comment by ayeung** [comment]
@zhihuitang Just made a change to encode all values of the query param.  I tested it with the example you gave (thanks for providing this).  The fix for this should be out in the next release.

**Comment by zhihuitang** [comment]
thanks
