### ISSUE TITLE
App crash: WindowManager$BadTokenException

### ISSUE THREAD

**Issue by claust** [SurveyMonkey/surveymonkey-android-sdk#37]
The SDK makes the app crash, seems to be due to poor lifecycle handling in the SMFeedbackFragment. It launches an AsyncTask (RetrieveSPageTask), which later blows up in onPostExecute if the user has moved on.

I see the following stacktrace:

`Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@2779dcb is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:567)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:272)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
       at android.app.Dialog.show(Dialog.java:298)
       at com.surveymonkey.surveymonkeyandroidsdk.SurveyMonkey$1.onPostExecute(Unknown Source)
       at com.surveymonkey.surveymonkeyandroidsdk.SurveyMonkey$1.onPostExecute(Unknown Source)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5306)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

**Comment by Vandalko** [comment]
Few days ago I've got a very similar crash
```java
Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{31d8b5a V.E...... R.....ID 0,0-1140,0} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
       at android.app.Dialog.dismissDialog(Dialog.java:362)
       at android.app.Dialog.dismiss(Dialog.java:345)
       at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment$SMWebviewClient.onPageFinished(SMFeedbackFragment.java:325)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:531)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:188)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by danmcd604** [comment]
Looks like this will occur when the activity context your using in the _AlertDialog.Builder_ is finishing or has finished before showing the dialog.

 **For me the error occurs at:**

_com.surveymonkey.surveymonkeyandroidsdk.SurveyMonkey$1.onPostExecute(SurveyMonkey.java:122)_

**For the task eecuted at:**

 _com.surveymonkey.surveymonkeyandroidsdk.SurveyMonkey$1.onPostExecute(SurveyMonkey.java:130)_

We're compiling the sdk with version:
`'com.surveymonkey:surveymonkey-android-sdk:1.0.5'`

Didn't investigate too much on how to reproduce the issue specifically in your code, but you can probably install an example app and start the feedback intercept process with a 0 _afterInstallInterval_ so that the survey dialog prompts right away, then add a built in wait to the _RetrieveSPageTask_'s _doInBackground()_ method and finish the activity that called the sdk's _onStart()_ method before that task's _onPostExecute()_ is called.

An simple example of reproducing the exception in an activity (_ExampleActivity_) is here:

```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        // Execute task:
        new TestAsyncTask().execute(null,null);
        finish();
    }

    class TestAsyncTask extends AsyncTask<Void,Void,String> {
        @Override
        public String doInBackground(Void...voids){
            try{
                Thread.sleep(5000);
            }catch (Exception e){
                e.printStackTrace();
            }

            return "";
        }

        @Override
        public void onPostExecute(String result) {
            AlertDialog.Builder builder = new AlertDialog.Builder(ExampleActivity.this);
            LayoutInflater inflater = getLayoutInflater();

            View root = inflater.inflate(R.layout.example_view,null);

            builder.setView(root);

            builder.create().show();
        }
    }
```

I think a simple check to see if the activity is finished would be fine. You can do something like this to fix the issue (don't necessarily have to use a weak reference):

https://stackoverflow.com/questions/18662239/android-view-windowmanagerbadtokenexception-unable-to-add-window-on-buider-sl

**Comment by ayeung** [comment]
@danmcd604 Thanks for the great example!  I've added an isFinishing() check as you suggested.  It should be available in the next version.
