### ISSUE TITLE
SimpleSurvey sample app - SMFeedbackActivity has leaked IntentReceiver

### ISSUE THREAD

**Issue by cpeppas** [SurveyMonkey/surveymonkey-android-sdk#4]
Although the app successfully works, I get this in the logcat when I complete a very simple single page survey.

Activity com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity has leaked IntentReceiver com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity$ConnectivityMonitor@d22ccf2 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                             android.app.IntentReceiverLeaked: Activity com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity has leaked IntentReceiver com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity$ConnectivityMonitor@d22ccf2 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                 at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:903)
                                                                                 at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:704)
                                                                                 at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1651)
                                                                                 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1631)
                                                                                 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1625)
                                                                                 at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:489)
                                                                                 at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity.onCreate(SMFeedbackActivity.java:67)
                                                                                 at android.app.Activity.performCreate(Activity.java:5990)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by benleiken** [comment]
@cpeppas This should have been fixed in the release yesterday, can you confirm that you're using the most recent SDK .aar file?
