### ISSUE TITLE
Not working on older devices (tested: Android 4.4.2)

### ISSUE THREAD

**Issue by swenmeeuwes** [SurveyMonkey/surveymonkey-android-sdk#56]
The SDK is not working on older Android devices (tested on Android 4.4.2).
It produces the following;
`09-10 13:56:45.226 22024-22150/com.xxx.xxx.xxx W/Server error: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x797110e8: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x743317e8:0x00000000)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:469)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:1014)
        at com.android.okhttp.Connection.connect(Connection.java:955)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:411)
        at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:343)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
        at com.surveymonkey.surveymonkeyandroidsdk.loaders.RetrieveSPageTask.doInBackground(RetrieveSPageTask.java:30)
        at com.surveymonkey.surveymonkeyandroidsdk.loaders.RetrieveSPageTask.doInBackground(RetrieveSPageTask.java:20)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x797110e8: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x743317e8:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:426)
        	... 17 more
09-10 13:56:45.226 22024-22024/com.xxxx.xxxx.xxxx W/System.err: org.json.JSONException: No value for survey_status
        at org.json.JSONObject.get(JSONObject.java:355)
        at org.json.JSONObject.getJSONObject(JSONObject.java:574)
        at com.surveymonkey.surveymonkeyandroidsdk.SurveyMonkey$2.onPostExecute(SurveyMonkey.java:159)
        at com.surveymonkey.surveymonkeyandroidsdk.SurveyMonkey$2.onPostExecute(SurveyMonkey.java:154)
        at android.os.AsyncTask.finish(AsyncTask.java:632)
        at android.os.AsyncTask.access$600(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5476)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)`

I was able to fix this by installing a newer security provider, using google play services:
https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han

**Comment by ayeung** [comment]
Thanks for reporting this.  We are actually bumping up the minsdk version to 21 as of the latest version (2.0.0) so Android 4.X is no longer supported.
