### ISSUE TITLE
DEX issues with android sdk

### ISSUE THREAD

**Issue by kapil-lokhande** [SurveyMonkey/surveymonkey-android-sdk#57]
Hi Team 
I encountered following error after the build of my app 
I am using monkey survey services in for my apps for the first time and i am registered account holder (kapil.lokhande@media4u.com) of survey monkey with paid plan.
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/surveymonkey/surveymonkeyandroidsdk/BuildConfig;
Error:com.android.dex.DexException: Multiple dex files define Lcom/surveymonkey/surveymonkeyandroidsdk/BuildConfig;
Error: at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error: at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error: at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error: at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error: at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error: at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error: at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error: at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/surveymonkey/surveymonkeyandroidsdk/BuildConfig;

Regards, 
Kapil

**Comment by ayeung** [comment]
Did you already enable multidex?

android {
   ...
   defaultConfig {
      ...
      multiDexEnabled true
   }
}
