### ISSUE TITLE
App is  Crashing When i click on submit button

### ISSUE THREAD

**Issue by nitika-bhatia** [SurveyMonkey/surveymonkey-android-sdk#59]
After I am done with the survey , I click on Submit button . This crash is random and happening on android 8.0
Here are the logs -:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragmentListener.onFetchRespondentSuccess(org.json.JSONObject)' on a null object reference
        at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment.handleRespondent(SMFeedbackFragment.java:207)
        at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment.onGetRespondentTaskLoadFinished(SMFeedbackFragment.java:195)
        at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment$2.onLoadFinished(SMFeedbackFragment.java:176)
        at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment$2.onLoadFinished(SMFeedbackFragment.java:168)
        at android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:221)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:156)
        at android.support.v4.content.Loader.deliverResult(Loader.java:130)
        at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:257)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:82)
        at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
        at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by ayeung** [comment]
Added some changes that will hopefully fix this in 1.0.7

**Comment by ayeung** [comment]
Just released 2.0.0.  Check it out when you get the chance.  I'll be closing this issue for now, feel free to reopen and/or comment if you are still having issues.

Note that I did run into a situation where the previous version of the library was cached on Android Studio, so I would also invalidate the cache to make sure you are grabbing the latest if you run into any issues.
