### ISSUE TITLE
Fatal Exception: android.view.WindowManager$BadTokenException 

### ISSUE THREAD

**Issue by gerc99** [SurveyMonkey/surveymonkey-android-sdk#68]
`Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@7ab2778 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:785)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:298)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
       at android.app.Dialog.show(Dialog.java:325)
       at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment$SMWebviewClient.onPageStarted(SMFeedbackFragment.java:300)
       at ib.c(ib.java:314)
       at Ae.handleMessage(Ae.java:20)
       at android.os.Handler.dispatchMessage(Handler.java:102)`

**Comment by thduc89** [comment]
I faced this issue, too @gerc99 . I dug into the SDK code and saw that onPageStarted method call `mProgressDialog.show()`, and that dialog is created using the crashed activity we passed into it, and `onPageStarted` method is called by `onPostExecute` method of an AsyncTask named `RetrieveSPageTask` which is never got canceled in `onDestroy` method of SMFeedbackFragment.

**Comment by thduc89** [comment]
Hi @ayeung , your SDK is great, I really love it. But I have this only one issue so far and the crash logs are getting more and more, please take a look at this, it's really urgent. Thank you so much.

**Comment by theBradfo** [comment]
Also seeing this and is inconsistently reproducible on a device if the user hits the native "back" button within the survey fragment.
